FROM node:24-alpine AS builder
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci --production=false
COPY . .
ARG BRAND
ARG DIRECTUS_URL
ARG DIRECTUS_TOKEN
ARG CF_ACCESS_CLIENT_ID
ARG CF_ACCESS_CLIENT_SECRET
ARG BOOKING_AID
ARG GETYOURGUIDE_PARTNER
ARG WIJNVOORDEEL_TRACKING_ID
ARG SKYSCANNER_PARTNER
ARG REISVERZEKERING_PARTNER
ENV BRAND=${BRAND} DIRECTUS_URL=${DIRECTUS_URL} DIRECTUS_TOKEN=${DIRECTUS_TOKEN} CF_ACCESS_CLIENT_ID=${CF_ACCESS_CLIENT_ID} CF_ACCESS_CLIENT_SECRET=${CF_ACCESS_CLIENT_SECRET} BOOKING_AID=${BOOKING_AID} GETYOURGUIDE_PARTNER=${GETYOURGUIDE_PARTNER} WIJNVOORDEEL_TRACKING_ID=${WIJNVOORDEEL_TRACKING_ID} SKYSCANNER_PARTNER=${SKYSCANNER_PARTNER} REISVERZEKERING_PARTNER=${REISVERZEKERING_PARTNER}
RUN npm run build

FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
RUN printf 'server {\n  listen 3101;\n  root /usr/share/nginx/html;\n  index index.html;\n  location / {\n    try_files $uri $uri/ /index.html;\n  }\n}\n' > /etc/nginx/conf.d/default.conf
EXPOSE 3101
CMD ["nginx", "-g", "daemon off;"]
