server {
    listen 80;
    server_name vinomartino.travel preview.vinomartino.com;

    root /usr/share/nginx/html/nl;
    index index.html;

    location /_astro/ {
        alias /usr/share/nginx/html/_astro/;
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
